
import './globals.css'
import Header from '@/components/Header/Header'
import { Open_Sans, Roboto_Mono } from 'next/font/google'


const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  //👇 Add variable to our object
  variable: '--font-opensans',
})

//👇 Configure the object for our second font
const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html
    lang="en"
    className={`${openSans.variable} ${robotoMono.variable} font-sans`}
  >
      <body >
            <Header  />
        
              {children}
        
        
        </body>
    </html>
  )
}
